title: Atlas to Earth
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.0625
  brandStrength: 1
  lightness: 0.5625
  brandColors:
    - '#2f2f2f'
    - '#ffffff'
    - '#4d4d4d'
    - '#a2a2a2'
    - '#cacaca'
  rhythmicContrast: 0.5
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: Atlas to Earth
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.77273
layout_spectrum: 0.93322
