name: Atlas to Earth
favicon: null
layout_spectrum: 0.93322
typography_spectrum: 0.77273
title: Atlas to Earth
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2f2f2f'
    - '#ffffff'
    - '#4d4d4d'
    - '#a2a2a2'
    - '#cacaca'
  brandStrength: 0.625
  lightness: 0.5625
  saturation: 0.0625
  rhythmicContrast: 0.5
purpose: []
